apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mecvgq3px-nodejs 
  janus-idp.io/tekton: mecvgq3px-nodejs
  backstage.io/kubernetes-id: mecvgq3px-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mecvgq3px-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml