apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mecvgq3px-nodejs
  janus-idp.io/tekton: mecvgq3px-nodejs
  backstage.io/kubernetes-id: mecvgq3px-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mecvgq3px-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
