apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mecvgq3px-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mecvgq3px-nodejs 
  name: mecvgq3px-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mecvgq3px-nodejs 
